---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.3-22-g54d1b7b
_src_path: .
app_description: open and extensible continuous delivery solution for Kubernetes.
app_name: flux
app_repo: https://github.com/fluxcd/flux2
app_version_prefix: v
app_website: https://fluxcd.io
custom_arch_enabled: true
custom_arch_yaml:
    aarch64*: arm64
    armv5*: arm
    armv6*: arm
    armv7*: arm
    x86_64: amd64
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_os_enabled: false
download_checksum_cmd: '256'
download_checksum_enabled: true
download_checksum_link: https://github.com/fluxcd/flux2/releases/download/v{version}/flux_{version}_checksums.txt
download_link: https://github.com/fluxcd/flux2/releases/download/v{version}/flux_{version}_{os}_{arch}.tar.gz
download_location: flux
download_strip: 0
download_type: archive-file
install_type: single-file
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-flux2
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-flux2
test_cmd_args: ''
