---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.3-50-gd56c40f
_src_path: /Users/kamontat/Desktop/Personal/asdf-plugin-template
app_desc: A open and extensible continuous delivery solution for Kubernetes.
app_name: flux
app_repo: https://github.com/fluxcd/flux2
app_website: https://fluxcd.io
archive_conf_path: ''
archive_conf_strip: 0
archive_enabled: true
archive_regex: (\.tar\.gz|\.tgz|\.zip)$
checksum_conf_algorithm: 256
checksum_enabled: true
checksum_url: https://github.com/fluxcd/flux2/releases/download/v{version}/flux_{version}_checksums.txt
custom_arch_enabled: true
custom_arch_yaml:
    aarch64*: arm64
    armv5*: arm
    armv6*: arm
    armv7*: arm
    x86_64: amd64
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_os_enabled: false
custom_require_commands: ''
download_url: https://github.com/fluxcd/flux2/releases/download/v{version}/flux_{version}_{os}_{arch}.tar.gz
gpg_enabled: false
install_map_enabled: true
install_map_method: move
install_map_yaml:
    flux: bin/flux
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-flux2
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-flux2.git
source_enabled: false
test_cmd_args: --version
version_file_enabled: false
version_prefix: v
