---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.0
_src_path: gh:kc-workspace/asdf-plugin-template.git
app_download_link: https://github.com/fluxcd/flux2/releases/download/v${version}/flux_${version}_${os}_${arch}.tar.gz
app_git_repo: https://github.com/fluxcd/flux2
app_name: flux
app_strip_component: 0
git_remote: https://github.com/kc-workspace/asdf-flux2.git
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-flux2
plugin_org: kc-workspace
